#ifndef _CONSTANTES_
#define _CONSTANTES_

//Ecran
const int WINDOW_WIDTH = 1000;
const int WINDOW_HEIGHT = 700;
const int SIZE_TEXT = 20;
const int LARGEUR_BOUTON = 300;
const int HAUTEUR_BOUTON = 80;

//Batiment
const int DIMENSION_SPRITE = 100;
const int RESISTANCE = 200;

//Foyer
const int QUANTITE_RESSOURCES_MAX_FOYER = 80;
const int QUANTITE_RESSOURCES_MAX_ARTISAN = 10;

//PERSONNAGE
const int POINTS_DE_VIE = 30;
const int DEGATS_COMBATTANT = 2;
const int DIMENSION_PERSO = (DIMENSION_SPRITE*2)/3;

//RESSOURCE
const int QUANTITE_RESSOURCE = 200;

#endif
